#################################################################################
########            Pipeline to build on pull requests                   ########
#################################################################################
name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-build
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: self-hosted-hoprnet-small
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: hoprnet/hopr-workflows/actions/setup-node-js@setup-node-js-v1
        with:
          node_version: ${{ matrix.node-version }}

      - name: Building
        run: yarn build

      - name: Linting
        run: yarn lint:ci

      - name: Formatting
        run: yarn format:ci

      - name: Testing
        run: yarn test
  build-docker:
    name: Docker
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@build-docker-v1
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      build_matrix: >-
        [
          {
            "runner": "self-hosted-hoprnet-bigger",
            "architecture": "x86_64-linux",
            "build_command": "nix run .#docker-x86_64-linux"
          }
        ]
      build_file: package.json
      docker_image_name: ${{ vars.DOCKER_IMAGE_NAME }}
      docker_image_format: docker
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
