---
name: Main
on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: false

permissions: {}

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yaml
    permissions:
      contents: read

  docker:
    name: Docker
    needs: checks
    uses: ./.github/workflows/docker.yaml
    permissions:
      contents: read
      packages: write
    with:
      push: true
